### ISSUE TITLE
Progress Percentage alignment issue in mumble dark

### ISSUE THREAD

**Issue by sharunkumar** [jagannatharjun/qbt-theme#51]
![image](https://user-images.githubusercontent.com/715417/112125984-0193be80-8bea-11eb-83b6-2db013fd06e4.png)

**Comment by cbzcbz** [comment]
Already fixed in the latest release dated 1 december 2020 !!

**Comment by BrandonCardoso** [comment]
Also in breeze-dark

**Comment by RabidWolf** [comment]
Yep something broke in 4.3.4 for me.

**Comment by fr3quency** [comment]
> Already fixed in the latest release dated 1 december 2020 !!

Latest 4.3.4 version brought back this issue.

**Comment by Dark-Yox** [comment]
> - BUGFIX: Various drawing improvements of progress bar (Chocobo1)

That's probably what broke the progress bar in the version 4.3.4

**Comment by cbzcbz** [comment]
> Latest 4.3.4 version brought back this issue.

My apologies , I'm still on 4.3.3.

**Comment by lfechio12** [comment]
This problem has already been fixed in the other themes, but continues in the mumble-dark.qtheme theme

**Comment by Dark-Yox** [comment]
I can confirm the problem is still here for the mumble-dark.

**Comment by fr3quency** [comment]
The problem has been fixed in 4.3.4.1.

**Comment by lfechio12** [comment]
I just upgraded to version 4.3.4.1 and as the user fr3quency said the problem was resolved

**Comment by Dark-Yox** [comment]
Yes, problem solved. I guess that we can close this issue now.

**Comment by sharunkumar** [comment]
Problem solved in 4.3.4.1

**Comment by Nisarg12** [comment]
I'm on 4.3.4.1 and it is still being clipped, using mumble dark v2.3.

![image](https://user-images.githubusercontent.com/28131554/112709897-1373ab00-8ee3-11eb-9b2f-574a9c805997.png)
